#!/usr/bin/env bash

set -e

files=".dotfiles .zsh-plugins .vim-plugins .tmux .tmuxline .git-scripts .fonts"

fast=0
small=0

for arg; do
    case "$arg" in
        (fast|f)
            fast=$(($fast + 1))
            ;;

        (small|s)
            small=$(($small + 1))
            ;;
    esac
done

cd ~

for file in $files; do
    if ! [ -d "$file" ] && ! [ -f "$file" ]; then
        echo "$file does not exist" >&2
        exit 1
    fi
done

tar cf /tmp/dotfiles.tar $files

case "$fast" in
    (0)
        ;;

    (1)
        gzip -c -9 </tmp/dotfiles.tar >dotfiles.tar.gz &
        zip -rq -9 dotfiles.zip $files &
        ;;

    (*)
        gzip -c </tmp/dotfiles.tar >dotfiles.tar.gz &
        zip -rq dotfiles.zip $files &
        ;;
esac

wait

case "$small" in
    (0)
        ;;

    (1)
        bzip2 -c </tmp/dotfiles.tar >dotfiles.tar.bz2
        ;;

    (2)
        bzip2 -9 -c </tmp/dotfiles.tar >dotfiles.tar.bz2
        ;;

    (3)
        xz -T $(($(nproc) - 1)) -c </tmp/dotfiles.tar >dotfiles.tar.xz
        ;;

    (4)
        xz -T $(($(nproc) - 1)) -c -9 </tmp/dotfiles.tar >dotfiles.tar.xz
        ;;

    (5)
        xz -T $(($(nproc) - 1)) -c -9e </tmp/dotfiles.tar >dotfiles.tar.xz
        ;;
esac
