#!/bin/sh

cd "$HOME/Joel/software/vim-plugins"

for plugin in *; do
    cd "$HOME/Joel/software/vim-plugins/$plugin"

    git upa >/dev/null 2>&1

    if [ -z "$(find "$HOME/.vim/bundle" -maxdepth 1 -type d -name \
        "$plugin")" ]; then

        mkdir -p "$HOME/.vim/bundle/$plugin"
    else
        if [ -z "$(find "$HOME/.vim/bundle/$plugin" -maxdepth 1 -type d -name \
            "plugin")" ]; then

            continue
        fi
    fi

    cp -r * "$HOME/.vim/bundle/$plugin"
done
