#!/bin/sh

if [ ! -d "$HOME/.zsh-plugins" ]; then
    echo "error: '$HOME/.zsh-plugins' is not a directory" >&2
    exit 1
fi
cd "$HOME/.zsh-plugins"

nprocs="$(lscpu | awk '$1 == "CPU(s):" {print $2}')"
nplugins="$(echo * | wc -w)"

for plugin in *; do
    (
        cd "$HOME/.zsh-plugins/$plugin" 2>/dev/null || exit

        sleep $(($RANDOM % ($nplugins / (($nprocs / 2) - 1) + 1))) || exit

        git wipe >/dev/null

        git submodule update --init --recursive >/dev/null 2>&1
        git update-all >/dev/null 2>&1

        git checkout --quiet master
    ) &
done

wait
