#!/bin/sh

if [ ! -d "$HOME/.vim-plugins" ]; then
    echo "error: '$HOME/.vim-plugins' is not a directory" >&2
    exit 1
fi
cd "$HOME/.vim-plugins"

mkdir -p "$HOME/.vim/autoload"
mkdir -p "$HOME/.vim/bundle"

cp vim-pathogen/autoload/pathogen.vim "$HOME/.vim/autoload"

for plugin in *; do
    cd "$HOME/.vim-plugins/$plugin"

    git submodule update --init --recursive >/dev/null 2>&1
    git upa >/dev/null 2>&1

    if [ -z "$(find "$HOME/.vim/bundle" -maxdepth 1 -type d -name \
        "$plugin")" ]; then

        mkdir "$HOME/.vim/bundle/$plugin"
    else
        if [ -z "$(find "$HOME/.vim/bundle/$plugin" -maxdepth 1 -type d -name \
            "plugin")" ]; then

            continue
        fi
    fi

    # Note: DO NOT first remove what is in there; just copy over and replace.
    # If you remove first, then essential files for YouCompleteMe will need to
    # be copied over again manually.
    cp -r * "$HOME/.vim/bundle/$plugin"
done
