#!/bin/sh

if [ ! -d "$1" ]; then
    echo "Error: invalid vim plugin path '$1'" >&2
    exit 1
fi

cd "$1"

cp vim-pathogen/autoload/pathogen.vim "$HOME/.vim/autoload/"

for plugin in *; do
    cd "$1$plugin"

    git upa >/dev/null 2>&1

    if [ -z "$(find "$HOME/.vim/bundle" -maxdepth 1 -type d -name \
        "$plugin")" ]; then

        mkdir -p "$HOME/.vim/bundle/$plugin"
    else
        if [ -z "$(find "$HOME/.vim/bundle/$plugin" -maxdepth 1 -type d -name \
            "plugin")" ]; then

            continue
        fi
    fi

    cp -r * "$HOME/.vim/bundle/$plugin"
done
