#!/bin/sh

if [ ! -d "$1" ]; then
    echo "Error: invalid vim plugin path '$1'" >&2
    exit 1
fi

cd "$1"

for plugin in *; do
    cd "$1$plugin"

    git submodule update --init --recursive >/dev/null 2>&1
    git upa >/dev/null 2>&1
done
