#!/bin/sh

if [ ! -d "$HOME/.zsh-plugins" ]; then
    echo "error: '$HOME/.zsh-plugins' is not a directory" >&2
    exit 1
fi
cd "$HOME/.zsh-plugins"

for plugin in *; do
    (
        cd "$HOME/.zsh-plugins/$plugin" 2>/dev/null || exit

        git submodule update --init --recursive >/dev/null 2>&1
        git update-all >/dev/null 2>&1
    ) &
done
